source 'http://rubygems.org'

gem 'middleman', '~>3.2.0'
gem 'haml'
gem 'redcarpet'
gem 'nokogiri'

gem 'compass'
gem 'bootstrap-sass', '~> 3.0.2.0'

gem 'middleman-livereload', '~> 3.1.0'
gem 'middleman-pry'

gem 'middleman-gh-pages'
